PROGS_MUTEX_CHASER_OBJS := mutex_test.o
PROGS_MUTEX_CHASER_OBJS := $(PROGS_MUTEX_TEST_OBJS:%=$(TDIR)/mutex_test/%)
ALL_OBJS += $(PROGS_MUTEX_TEST_OBJS)

$(TDIR)/bin/mutex_test : $(TSTART) $(PROGS_MUTEX_TEST_OBJS) $(TLIBC)
